// scripts/build-emails.mjs
//
// Compiles the MJML email sources in server/utils/emails/mjml/*.mjml into a
// single generated module, server/utils/emails/compiled.ts, that exports each
// email's HTML as a plain string (Handlebars tokens left intact). The runtime
// (welcome.ts / password-reset.ts) fills those tokens per-send with Handlebars,
// so MJML itself never ships in the server bundle — it stays a devDependency.
//
//   Run:  npm run build:emails   (or: node scripts/build-emails.mjs)
//
// Re-run whenever you edit a .mjml source, and commit the regenerated
// compiled.ts alongside it.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, basename } from 'node:path'
import mjml2html from 'mjml'

const here = dirname(fileURLToPath(import.meta.url))
const mjmlDir = join(here, '../server/utils/emails/mjml')
const outFile = join(here, '../server/utils/emails/compiled.ts')

// welcome -> welcome, password-reset -> passwordReset
const toCamel = (name) => name.replace(/-([a-z])/g, (_, c) => c.toUpperCase())

const sources = readdirSync(mjmlDir).filter((f) => f.endsWith('.mjml')).sort()
if (sources.length === 0) {
  console.error(`No .mjml files found in ${mjmlDir}`)
  process.exit(1)
}

const exportLines = []
let failed = false

for (const file of sources) {
  const src = readFileSync(join(mjmlDir, file), 'utf8')
  const { html, errors } = await mjml2html(src, {
    validationLevel: 'soft',
    minify: false,
    filePath: join(mjmlDir, file),
  })

  if (errors && errors.length) {
    failed = true
    console.error(`✗ ${file} — ${errors.length} MJML error(s):`)
    for (const e of errors) console.error(`    ${e.formattedMessage || e.message}`)
    continue
  }

  const ident = `${toCamel(basename(file, '.mjml'))}Html`
  // JSON.stringify yields a safe, import-clean double-quoted JS string literal —
  // no backtick / ${ } collisions with the email markup.
  exportLines.push(`export const ${ident} = ${JSON.stringify(html)}`)
  console.log(`✓ ${file} → ${ident} (${html.length} bytes)`)
}

if (failed) {
  console.error('\nBuild aborted — fix the MJML errors above and re-run.')
  process.exit(1)
}

const banner =
  `// AUTO-GENERATED by scripts/build-emails.mjs — do not edit by hand.\n` +
  `// Source: server/utils/emails/mjml/*.mjml — run \`npm run build:emails\` to regenerate.\n` +
  `/* eslint-disable */\n\n`

writeFileSync(outFile, banner + exportLines.join('\n') + '\n')
console.log(`\nWrote ${outFile}`)
